baseURL: "https://www.geekyhub.in"
title: GeekyHub
pagination.pagerSize: 5
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

    # l2:
    #     languageName: "Lang2"
    #     weight: 2
    #     title: PaperModL2
    #     profileMode:
    #         enabled: true
    #         title: PaperMod
    #         # imageUrl: "#"
    #         # imageTitle: my image
    #         # imageWidth: 120
    #         # imageHeight: 120
    #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Tags
    #               url: tags
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: Tags
    #               url: tags
    #               weight: 10
    #             - name: Categories
    #               url: categories
    #               weight: 10
    #             - name: Series
    #               url: series
    #               weight: 10
    #             - name: NullLink
    #               url: "#"
    #             - name: NullLink2
    #               url: "#"
    #             - name: NullLink3
    #               url: "#"

    # l3:
    #     languageName: "Langrtl"
    #     languagedirection: rtl
    #     weight: 3
    #     title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     menu:
    #         main:
    #             - name: Tags
    #               url: tags
    #               weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Geekyhub"
    author: Vikas Kumar
    # author: ["Me", "You"] # multiple authors
    ShowFullTextinRSS: true
    ShowCodeCopyButtons: true
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: false
    comments: true
    ShowRssButtonInSectionTermList: true
    ShowPostNavLinks: true
    # disableSpecial1stPost: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    schema:
      publisherType: "Person"

    editPost:
      URL: "https://github.com/vikas-0/GeekyHub/tree/master/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true #

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Blog
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            Welcome to GeekyHub.

            - **GeekyHub** is a place to share my thoughts, opinion and Experiences on Technologies.

    socialIcons:
        # - name: twitter
        #   url: "https://twitter.com/iVikasKr"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/4716643/vikas-kumar"
        - name: linkedin
          url: "https://www.linkedin.com/in/vikas-kr/"
        - name: github
          url: "https://github.com/vikas-0"
        - name: telegram
          url: "https://t.me/vikaskmr"
        - name: instagram
          url: "https://www.instagram.com/vikas_krr/"
        - name: twitter
          url: "https://twitter.com/iVikasKr"
        - name: rss
          url: "index.xml"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
    googleAnalytics:
        id: "G-7N85P7G3FG"

# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname: "geekyhub"
